server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://127.0.0.1:8000/pygeoapi
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  languages:
    - en-US
  limits:
    default_items: 20
    max_items: 50
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: OpenStreetMap

metadata:
  identification:
    title:
      en: DHIS2 EO API
    description:
      en: OGC API facade for EO services
    keywords:
      en:
        - EO
        - DHIS2
    terms_of_service: https://dhis2.org
    url: https://dhis2.org
  license:
    name: CC-BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: DHIS2 EO API
    url: https://dhis2.org
  contact:
    name: DHIS2
    position: Team
    email: climate@dhis2.org

resources: {}
